-- Initial schema for the therapist portal. Portable across PostgreSQL (production) and
-- H2 in PostgreSQL mode (development). All timestamps are stored in UTC.

CREATE TABLE therapists (
    id            UUID         PRIMARY KEY,
    first_name    VARCHAR(255) NOT NULL,
    middle_name   VARCHAR(255),
    last_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    phone         VARCHAR(255),
    date_of_birth DATE,
    address       VARCHAR(255),
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    CONSTRAINT uk_therapists_email UNIQUE (email)
);

CREATE TABLE languages (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32)  NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_languages_code UNIQUE (code)
);

CREATE TABLE therapist_languages (
    therapist_id UUID    NOT NULL REFERENCES therapists (id),
    language_id  INTEGER NOT NULL REFERENCES languages (id),
    PRIMARY KEY (therapist_id, language_id)
);

CREATE TABLE slots (
    id           UUID         PRIMARY KEY,
    therapist_id UUID         NOT NULL REFERENCES therapists (id),
    slot_time    TIMESTAMP(6) NOT NULL,
    status       VARCHAR(32)  NOT NULL,
    version      BIGINT,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_therapist_slot_time UNIQUE (therapist_id, slot_time)
);

CREATE TABLE bookings (
    id                  UUID          PRIMARY KEY,
    therapist_id        UUID          NOT NULL REFERENCES therapists (id),
    slot_id             UUID          REFERENCES slots (id),
    customer_name       VARCHAR(255)  NOT NULL,
    customer_email      VARCHAR(255),
    customer_phone      VARCHAR(255),
    customer_country    VARCHAR(255),
    start_time          TIMESTAMP(6)  NOT NULL,
    end_time            TIMESTAMP(6)  NOT NULL,
    booking_reason      VARCHAR(1000),
    status              VARCHAR(32)   NOT NULL,
    therapist_fee       NUMERIC(10, 2),
    assigned_at         TIMESTAMP(6),
    is_rescheduled      BOOLEAN       NOT NULL DEFAULT FALSE,
    previous_start_time TIMESTAMP(6),
    reschedule_reason   VARCHAR(255),
    marked_at           TIMESTAMP(6),
    version             BIGINT,
    created_at          TIMESTAMP(6)  NOT NULL,
    updated_at          TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_bookings_slot UNIQUE (slot_id)
);

CREATE INDEX idx_booking_therapist_start ON bookings (therapist_id, start_time);
CREATE INDEX idx_booking_status ON bookings (status);

CREATE TABLE booking_customer_languages (
    booking_id  UUID    NOT NULL REFERENCES bookings (id),
    language_id INTEGER NOT NULL REFERENCES languages (id),
    PRIMARY KEY (booking_id, language_id)
);
